yml
name: My-Hardware-Detection-Workflow
on:
  push:
    branches: [main]
jobs:
  hardware-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install psutil
      - name: Detect Hardware
        run: |
          python3 ${GITHUB_WORKSPACE}/detect_hardware.py
