yml
name: Hardware Heroes Workflow
on:
  push:
    branches: [ main ]
jobs:
  hardware-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install psutil
      - name: Detect Hardware
        run: |
          python3 ../detect_hardware.py
