yml
name: Hardware Heroes Workflow
on:
  push:
    branches: [ main ]
jobs:
  hardware-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install psutil
      - name: Detect Hardware
        run: |
          python detect_hardware.py
